name: Test Calculator

on:
  repository_dispatch:
    types: [run_tests]

jobs:
  test_calculator:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Fetch code and test files from Firestore
      run: |
        curl -X GET "https://firestore.googleapis.com/v1/projects/hw-test-5b55c/databases/(default)/documents/files/calculator.py?key=AIzaSyDrbZgqDXun4qv9j1Xqsevw-KOxPNFQ26U" -o calculator.py
        curl -X GET "https://firestore.googleapis.com/v1/projects/hw-test-5b55c/databases/(default)/documents/files/test_calculator.py?key=AIzaSyDrbZgqDXun4qv9j1Xqsevw-KOxPNFQ26U" -o test_calculator.py

    - name: Run tests and save results to a file
      run: python -m unittest test_calculator.py > test_results.txt

    # - name: Store test results in Firestore
    #   run: |
    #     test_results=$(cat test_results.txt)
    #     firestore_url="https://firestore.googleapis.com/v1/projects/hw-test-5b55c/databases/(default)/documents/test_results/test_results?key=AIzaSyDrbZgqDXun4qv9j1Xqsevw-KOxPNFQ26U"
    #     curl -X PATCH "$firestore_url" -H "Content-Type: application/json" -d "{\"fields\": {\"content\": {\"stringValue\": \"$test_results\"}}}"
